apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minecraft-operator
  template:
    metadata:
      labels:
        name: minecraft-operator
    spec:
      serviceAccountName: minecraft-operator
      containers:
        - name: minecraft-operator
          # Replace this with the built image name
          image: hoeghh/minecraft-operator
          command:
          - minecraft-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "minecraft-operator"
